## Prepare Training Data

In [1]:
import json
import torchaudio
import matplotlib.pyplot as plt
import torch
from datetime import time
import numpy as np

/Users/danilfedorovsky/miniforge3/envs/pytorch/lib/python3.9/site-packages/torchaudio/_internal/module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")


In [2]:
## decide what to load
SESSION = "S02"
transcript_path = "/Users/danilfedorovsky/Documents/10 Collection/00 Studium/00 Letztes Semester/Masterarbeit/Data/CHiME5/transcriptions/dev/" + SESSION + ".json"
#'/project/data_asr/CHiME5/data/CHiME5/transcriptions/dev/' + SESSION
data_path = "/Users/danilfedorovsky/Documents/10 Collection/00 Studium/00 Letztes Semester/Masterarbeit/Data/CHiME5/audio/dev/"

In [3]:
with open(transcript_path, 'r') as f:
    transcript = json.load(f)

In [4]:
u1_times = []
speaker_times = []
for entry in transcript:
    #print(entry["start_time"]["U01"])
    #print(entry["end_time"]["U01"])
    try:
        speaker_times.append([entry["speaker"],time.fromisoformat("0"+str(entry["start_time"]["U01"])+"0"),time.fromisoformat("0"+str(entry["end_time"]["U01"])+"0")])
        u1_times.append([time.fromisoformat("0"+str(entry["start_time"]["U01"])+"0"),time.fromisoformat("0"+str(entry["end_time"]["U01"])+"0")])
    except:
        # if redacted
        pass

print(speaker_times[0])
print(u1_times[0])
print(len(speaker_times)==len(u1_times))

['P05', datetime.time(0, 0, 40, 630000), datetime.time(0, 0, 43, 850000)]
[datetime.time(0, 0, 40, 630000), datetime.time(0, 0, 43, 850000)]
True


In [5]:
# 2h 28 min 24 s = 8904s
P05, sample_rate = torchaudio.load(data_path+"S02_P05.wav")
P06, _ = torchaudio.load(data_path+"S02_P06.wav")
P07, _ = torchaudio.load(data_path+"S02_P07.wav")
P08, _ = torchaudio.load(data_path+"S02_P08.wav")
U01, _ = torchaudio.load(data_path+"S02_U01.CH1.wav")
U012, _ = torchaudio.load(data_path+"S02_U01.CH2.wav")
#P05 = P05[0].reshape(1,-1)
#P06 = P06[0].reshape(1,-1)
#P07 = P07[0].reshape(1,-1)
#P08 = P08[0].reshape(1,-1)
print(U01.size(dim=1)/sample_rate, "seconds")

8904.04 seconds


In [6]:
# Cut the relevant segments
X = []#np.array([])#[]#torch.Tensor()
Y = []#np.array([])#[]#torch.Tensor()

def time_to_sample(time:time):
    return int(sample_rate*(time.hour*3600+time.minute*60+time.second+time.microsecond/1000000))

# Input
for start, end in u1_times:
    start = time_to_sample(start)
    end = time_to_sample(end)
    #X = torch.cat((X, U01[0][start:end]), 0)
    X.append([U01[0][start:end],U012[0][start:end]])
print("Input ready")

# Label
for speaker,start,end in speaker_times:
    #print(speaker,start,end)
    start = time_to_sample(start)
    end = time_to_sample(end)
    if speaker == "P05":
        #Y = torch.cat((Y, P05[0][start:end]), 0)
        #Y.append([P05[0][start:end],P05[1][start:end]])
        Y.append(P05[0][start:end])
    if speaker == "P06":
        #Y = torch.cat((Y, P06[0][start:end]), 0)
        Y.append(P06[0][start:end])
    if speaker == "P07":
        #Y = torch.cat((Y, P07[0][start:end]), 0)
        Y.append(P07[0][start:end])
    if speaker == "P08":
        #Y = torch.cat((Y, P08[0][start:end]), 0)
        Y.append(P08[0][start:end])

print("Label ready")
#print(X.size(0)==Y.size(0))
print(len(X)==len(Y))

Input ready
Label ready
True


## Training on CHIME

In [29]:
from torch.nn import Module, LeakyReLU, MaxPool1d, Conv2d, Linear, Softmax, BatchNorm1d, CrossEntropyLoss, BCELoss, Sigmoid, Tanh, LSTM, MSELoss
from torch import flatten
from torch.optim import Adam
import time
import torch
from pytorch_model_summary import summary
from tqdm import tqdm
import torchaudio

In [30]:
HIDDEN_SIZE=8
INIT_LR = 0.01
BATCH_SIZE = 1#64
SAMPLE_RATE = 16000
EPOCHS = 1
INPUT_CHANNEL = 2
REFERENCE_CHANNEL = 0

N_FFT = 1024
N_HOP = 256
stft = torchaudio.transforms.Spectrogram(
    n_fft=N_FFT,
    hop_length=N_HOP,
    power=None,
)
istft = torchaudio.transforms.InverseSpectrogram(n_fft=N_FFT, hop_length=N_HOP)
global i
i = 0

def prep_x(trainX,i):
        return stft((torch.cat((trainX[i][0].unsqueeze(1),trainX[i][1].unsqueeze(1)),1)).reshape(2,-1)).type(torch.complex64)

In [31]:
# # MASK NET

class MaskNet(Module):
    def __init__(self,noise=False):
        super(MaskNet, self).__init__()
        # First subnet for speech prediction
        self.type(torch.cfloat)
        self.noise = noise
        self.lstm = LSTM(input_size=INPUT_CHANNEL, hidden_size=HIDDEN_SIZE, num_layers=2, bidirectional=True)
        self.fc = Linear(in_features=HIDDEN_SIZE*2 ,out_features=1)
        self.sigmoid = Sigmoid()
        # Second subnet for noise prediction
        self.noise2 = noise
        self.lstm2 = LSTM(input_size=INPUT_CHANNEL, hidden_size=HIDDEN_SIZE, num_layers=2, bidirectional=True)
        self.fc2 = Linear(in_features=HIDDEN_SIZE*2 ,out_features=1)
        self.sigmoid2 = Sigmoid()

    def forward(self,x):
        # Speech prediction
        y = x.reshape(513,-1,INPUT_CHANNEL)#(513,251,INPUT_CHANNEL)
        y, (h_n, c_n) = self.lstm(y)
        y = self.fc(y).type(torch.double)
        speech_pred = self.sigmoid(y)
        speech_pred = speech_pred.reshape(513,-1).type(torch.cfloat)
        #print("speech_pred.shape",speech_pred.shape)

        # Noise prediction
        z = x.reshape(513,-1,INPUT_CHANNEL)
        z, (h_n, c_n) = self.lstm2(z)
        z = self.fc2(z).type(torch.double)
        noise_pred = self.sigmoid2(z)
        noise_pred = noise_pred.reshape(513,-1).type(torch.cfloat)

        psd_transform = torchaudio.transforms.PSD()
        psd_speech = psd_transform(x, speech_pred)
        psd_noise = psd_transform(x, noise_pred)
        mvdr_transform = torchaudio.transforms.SoudenMVDR()
        x = x.type(torch.cfloat)
        stft_souden = mvdr_transform(x, psd_speech, psd_noise, reference_channel=REFERENCE_CHANNEL)
        #print("stft_souden",stft_souden.shape)
        waveform_souden = istft(stft_souden, length=len(X[i][0]))#X[i].shape[-1])
        waveform_souden[waveform_souden != waveform_souden] = 1.0000e-10 
        print(waveform_souden)
        return waveform_souden.reshape(-1)

print(summary(MaskNet(),torch.zeros((INPUT_CHANNEL, 513, 251))))


tensor([0., 0., 0.,  ..., 0., 0., 0.], grad_fn=<AsStridedBackward0>)
------------------------------------------------------------------------------------------------
      Layer (type)                                 Output Shape         Param #     Tr. Param #
            LSTM-1     [513, 251, 16], [4, 251, 8], [4, 251, 8]           2,432           2,432
          Linear-2                                [513, 251, 1]              17              17
         Sigmoid-3                                [513, 251, 1]               0               0
            LSTM-4     [513, 251, 16], [4, 251, 8], [4, 251, 8]           2,432           2,432
          Linear-5                                [513, 251, 1]              17              17
         Sigmoid-6                                [513, 251, 1]               0               0
Total params: 4,898
Trainable params: 4,898
Non-trainable params: 0
----------------------------------------------------------------------------------------------

In [32]:

#device =  torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

model = MaskNet()#.to(device)
model.type(torch.complex64)

opt = Adam(model.parameters(), lr=INIT_LR)

lossMSE = MSELoss()

H = {
    "train_loss":[],
    "train_acc":[],
    "val_loss":[],
    "val_acc":[]
}

print("[INFO] training the network...")
#startTime = time.time()

for epoch in range(0, EPOCHS):
    print("Epoch:",epoch,"/1")
    # Train Mode
    model.train()
    
    # Initialize
    totalTrainLoss = 0
    totalValLoss = 0
    trainCorrect = 0
    valCorrect = 0

    trainX = X
    trainY = Y

    global i
    for i in tqdm(range(0,100)):#len(trainX))):
        (x, y) = (stft((torch.cat((trainX[i][0].unsqueeze(1),trainX[i][1].unsqueeze(1)),1)).reshape(2,-1)),trainY[i])#(trainX[i],trainY[i])
        #(x, y) = (x.to(device), y.to(device))
        # perform a forward pass and calculate the training loss
        #print(next(model.parameters()).is_cuda)
        print(x.shape)
        pred = model(x)
        loss = lossMSE(pred, y)

        #print("Loss:",loss)
        # zero out the gradients, perform the backpropagation step,
        # and update the weights
        opt.zero_grad()
        loss.backward()
        opt.step()
        # add the loss to the total training loss so far and
        # calculate the number of correct predictions
        totalTrainLoss += loss
        # trainCorrect += (pred.argmax(1) == y).type(
        #     torch.float).sum().item()

[INFO] training the network...
Epoch: 0 /1


  0%|          | 0/100 [00:00<?, ?it/s]

torch.Size([2, 513, 202])
tensor([ 0.0005,  0.0031,  0.0023,  ..., -0.0079, -0.0086, -0.0067],
       grad_fn=<AsStridedBackward0>)


  1%|          | 1/100 [00:02<04:11,  2.54s/it]

torch.Size([2, 513, 179])
tensor([ 0.0077,  0.0080,  0.0104,  ..., -0.0022, -0.0011,  0.0081],
       grad_fn=<AsStridedBackward0>)


  2%|▏         | 2/100 [00:04<03:08,  1.92s/it]

torch.Size([2, 513, 178])
tensor([-0.0002, -0.0041,  0.0015,  ...,  0.0246,  0.0301,  0.0425],
       grad_fn=<AsStridedBackward0>)


  3%|▎         | 3/100 [00:05<03:01,  1.87s/it]

torch.Size([2, 513, 118])
tensor([ 0.0152,  0.0047,  0.0156,  ..., -0.0150,  0.0050, -0.0195],
       grad_fn=<AsStridedBackward0>)


  4%|▍         | 4/100 [00:07<02:33,  1.60s/it]

torch.Size([2, 513, 295])
tensor([-0.0028, -0.0122, -0.0114,  ..., -0.0127, -0.0026, -0.0047],
       grad_fn=<AsStridedBackward0>)


  5%|▌         | 5/100 [00:10<03:26,  2.17s/it]

torch.Size([2, 513, 242])
tensor([1.7834e-03, 5.6711e-05, 4.6569e-03,  ..., 4.7405e-03, 1.0182e-02,
        1.1812e-02], grad_fn=<AsStridedBackward0>)


  6%|▌         | 6/100 [00:12<03:15,  2.08s/it]

torch.Size([2, 513, 127])
tensor([-0.0139, -0.0128,  0.0010,  ...,  0.0026, -0.0015, -0.0005],
       grad_fn=<AsStridedBackward0>)


  7%|▋         | 7/100 [00:13<02:47,  1.80s/it]

torch.Size([2, 513, 36])
tensor([ 0.0043,  0.0038, -0.0037,  ..., -0.0007,  0.0082,  0.0058],
       grad_fn=<AsStridedBackward0>)


  8%|▊         | 8/100 [00:14<02:12,  1.44s/it]

torch.Size([2, 513, 658])
tensor([ 0.0016,  0.0002,  0.0029,  ..., -0.1107, -0.0894, -0.0633],
       grad_fn=<AsStridedBackward0>)


  9%|▉         | 9/100 [00:21<04:51,  3.20s/it]

torch.Size([2, 513, 395])
tensor([-0.0302, -0.0271, -0.0459,  ..., -0.0437, -0.0223, -0.0267],
       grad_fn=<AsStridedBackward0>)


 10%|█         | 10/100 [00:24<05:03,  3.37s/it]

torch.Size([2, 513, 61])
tensor([0.0096, 0.0122, 0.0059,  ..., 0.0282, 0.0374, 0.0409],
       grad_fn=<AsStridedBackward0>)


 11%|█         | 11/100 [00:25<03:49,  2.58s/it]

torch.Size([2, 513, 477])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 12%|█▏        | 12/100 [00:29<04:33,  3.10s/it]

torch.Size([2, 513, 991])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 13%|█▎        | 13/100 [00:37<06:20,  4.37s/it]

torch.Size([2, 513, 221])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 14%|█▍        | 14/100 [00:38<05:05,  3.56s/it]

torch.Size([2, 513, 86])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 15%|█▌        | 15/100 [00:39<03:52,  2.73s/it]

torch.Size([2, 513, 124])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 16%|█▌        | 16/100 [00:40<03:05,  2.21s/it]

torch.Size([2, 513, 240])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 17%|█▋        | 17/100 [00:42<02:50,  2.05s/it]

torch.Size([2, 513, 199])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 18%|█▊        | 18/100 [00:43<02:33,  1.87s/it]

torch.Size([2, 513, 446])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 19%|█▉        | 19/100 [00:47<03:14,  2.40s/it]

torch.Size([2, 513, 330])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 20%|██        | 20/100 [00:50<03:27,  2.59s/it]

torch.Size([2, 513, 415])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 21%|██        | 21/100 [00:54<03:49,  2.91s/it]

torch.Size([2, 513, 541])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 22%|██▏       | 22/100 [00:58<04:26,  3.42s/it]

torch.Size([2, 513, 407])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 23%|██▎       | 23/100 [01:02<04:24,  3.43s/it]

torch.Size([2, 513, 24])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 24%|██▍       | 24/100 [01:02<03:17,  2.60s/it]

torch.Size([2, 513, 27])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 25%|██▌       | 25/100 [01:03<02:30,  2.00s/it]

torch.Size([2, 513, 111])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 26%|██▌       | 26/100 [01:04<02:10,  1.76s/it]

torch.Size([2, 513, 653])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 27%|██▋       | 27/100 [01:09<03:24,  2.80s/it]

torch.Size([2, 513, 461])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 28%|██▊       | 28/100 [01:13<03:42,  3.09s/it]

torch.Size([2, 513, 864])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 29%|██▉       | 29/100 [01:20<04:50,  4.10s/it]

torch.Size([2, 513, 471])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 30%|███       | 30/100 [01:23<04:39,  3.99s/it]

torch.Size([2, 513, 416])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 31%|███       | 31/100 [01:27<04:22,  3.81s/it]

torch.Size([2, 513, 59])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 32%|███▏      | 32/100 [01:28<03:17,  2.90s/it]

torch.Size([2, 513, 482])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 33%|███▎      | 33/100 [01:31<03:32,  3.17s/it]

torch.Size([2, 513, 1029])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 34%|███▍      | 34/100 [01:39<05:07,  4.65s/it]

torch.Size([2, 513, 764])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 35%|███▌      | 35/100 [01:45<05:17,  4.89s/it]

torch.Size([2, 513, 302])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 36%|███▌      | 36/100 [01:47<04:25,  4.15s/it]

torch.Size([2, 513, 553])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 37%|███▋      | 37/100 [01:52<04:25,  4.21s/it]

torch.Size([2, 513, 76])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 38%|███▊      | 38/100 [01:53<03:19,  3.22s/it]

torch.Size([2, 513, 595])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 39%|███▉      | 39/100 [01:57<03:40,  3.62s/it]

torch.Size([2, 513, 64])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 40%|████      | 40/100 [01:58<02:46,  2.77s/it]

torch.Size([2, 513, 384])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 41%|████      | 41/100 [02:01<02:47,  2.83s/it]

torch.Size([2, 513, 818])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 42%|████▏     | 42/100 [02:07<03:38,  3.76s/it]

torch.Size([2, 513, 1062])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 43%|████▎     | 43/100 [02:15<04:44,  4.99s/it]

torch.Size([2, 513, 203])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 44%|████▍     | 44/100 [02:16<03:43,  3.98s/it]

torch.Size([2, 513, 61])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 45%|████▌     | 45/100 [02:17<02:44,  2.99s/it]

torch.Size([2, 513, 90])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 46%|████▌     | 46/100 [02:18<02:07,  2.37s/it]

torch.Size([2, 513, 129])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 47%|████▋     | 47/100 [02:19<01:46,  2.02s/it]

torch.Size([2, 513, 474])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 48%|████▊     | 48/100 [02:23<02:12,  2.55s/it]

torch.Size([2, 513, 457])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 49%|████▉     | 49/100 [02:27<02:29,  2.92s/it]

torch.Size([2, 513, 1124])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 50%|█████     | 50/100 [02:35<03:50,  4.61s/it]

torch.Size([2, 513, 754])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 51%|█████     | 51/100 [02:41<04:01,  4.94s/it]

torch.Size([2, 513, 786])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 52%|█████▏    | 52/100 [02:47<04:10,  5.22s/it]

torch.Size([2, 513, 984])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 53%|█████▎    | 53/100 [02:54<04:31,  5.77s/it]

torch.Size([2, 513, 76])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 54%|█████▍    | 54/100 [02:55<03:19,  4.34s/it]

torch.Size([2, 513, 833])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 55%|█████▌    | 55/100 [03:01<03:42,  4.94s/it]

torch.Size([2, 513, 47])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 56%|█████▌    | 56/100 [03:02<02:42,  3.69s/it]

torch.Size([2, 513, 539])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 57%|█████▋    | 57/100 [03:06<02:47,  3.90s/it]

torch.Size([2, 513, 62])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 58%|█████▊    | 58/100 [03:07<02:04,  2.96s/it]

torch.Size([2, 513, 496])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 59%|█████▉    | 59/100 [03:11<02:13,  3.26s/it]

torch.Size([2, 513, 346])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 60%|██████    | 60/100 [03:14<02:04,  3.12s/it]

torch.Size([2, 513, 521])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 61%|██████    | 61/100 [03:18<02:16,  3.49s/it]

torch.Size([2, 513, 196])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 62%|██████▏   | 62/100 [03:20<01:52,  2.97s/it]

torch.Size([2, 513, 646])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 63%|██████▎   | 63/100 [03:25<02:13,  3.59s/it]

torch.Size([2, 513, 88])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 64%|██████▍   | 64/100 [03:26<01:40,  2.79s/it]

torch.Size([2, 513, 124])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 65%|██████▌   | 65/100 [03:27<01:21,  2.32s/it]

torch.Size([2, 513, 287])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 66%|██████▌   | 66/100 [03:30<01:21,  2.39s/it]

torch.Size([2, 513, 678])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 67%|██████▋   | 67/100 [03:35<01:49,  3.32s/it]

torch.Size([2, 513, 1041])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 68%|██████▊   | 68/100 [03:43<02:30,  4.69s/it]

torch.Size([2, 513, 428])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 69%|██████▉   | 69/100 [03:46<02:12,  4.29s/it]

torch.Size([2, 513, 936])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 70%|███████   | 70/100 [03:53<02:31,  5.07s/it]

torch.Size([2, 513, 582])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 71%|███████   | 71/100 [03:58<02:22,  4.92s/it]

torch.Size([2, 513, 76])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 72%|███████▏  | 72/100 [03:59<01:43,  3.70s/it]

torch.Size([2, 513, 161])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 73%|███████▎  | 73/100 [04:00<01:20,  2.98s/it]

torch.Size([2, 513, 49])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 74%|███████▍  | 74/100 [04:01<00:59,  2.29s/it]

torch.Size([2, 513, 1127])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 75%|███████▌  | 75/100 [04:10<01:49,  4.37s/it]

torch.Size([2, 513, 452])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 76%|███████▌  | 76/100 [04:17<02:00,  5.00s/it]

torch.Size([2, 513, 80])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 77%|███████▋  | 77/100 [04:18<01:33,  4.05s/it]

torch.Size([2, 513, 47])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 78%|███████▊  | 78/100 [04:19<01:08,  3.12s/it]

torch.Size([2, 513, 109])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 79%|███████▉  | 79/100 [04:22<01:00,  2.90s/it]

torch.Size([2, 513, 1001])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 80%|████████  | 80/100 [04:32<01:42,  5.14s/it]

torch.Size([2, 513, 98])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 81%|████████  | 81/100 [04:33<01:14,  3.92s/it]

torch.Size([2, 513, 799])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 82%|████████▏ | 82/100 [04:39<01:23,  4.63s/it]

torch.Size([2, 513, 790])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 83%|████████▎ | 83/100 [04:45<01:24,  4.97s/it]

torch.Size([2, 513, 49])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 84%|████████▍ | 84/100 [04:46<00:59,  3.70s/it]

torch.Size([2, 513, 667])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 85%|████████▌ | 85/100 [04:51<01:01,  4.11s/it]

torch.Size([2, 513, 291])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 86%|████████▌ | 86/100 [04:54<00:52,  3.75s/it]

torch.Size([2, 513, 1164])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 87%|████████▋ | 87/100 [05:04<01:12,  5.59s/it]

torch.Size([2, 513, 747])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 88%|████████▊ | 88/100 [05:09<01:06,  5.58s/it]

torch.Size([2, 513, 239])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 89%|████████▉ | 89/100 [05:11<00:49,  4.46s/it]

torch.Size([2, 513, 176])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 90%|█████████ | 90/100 [05:13<00:35,  3.53s/it]

torch.Size([2, 513, 780])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 91%|█████████ | 91/100 [05:18<00:38,  4.24s/it]

torch.Size([2, 513, 62])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 92%|█████████▏| 92/100 [05:19<00:25,  3.21s/it]

torch.Size([2, 513, 486])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 93%|█████████▎| 93/100 [05:24<00:25,  3.60s/it]

torch.Size([2, 513, 752])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 94%|█████████▍| 94/100 [05:32<00:29,  4.86s/it]

torch.Size([2, 513, 948])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 95%|█████████▌| 95/100 [05:40<00:29,  5.87s/it]

torch.Size([2, 513, 121])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 96%|█████████▌| 96/100 [05:41<00:18,  4.52s/it]

torch.Size([2, 513, 839])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 97%|█████████▋| 97/100 [05:48<00:15,  5.19s/it]

torch.Size([2, 513, 185])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 98%|█████████▊| 98/100 [05:50<00:08,  4.19s/it]

torch.Size([2, 513, 83])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


 99%|█████████▉| 99/100 [05:51<00:03,  3.30s/it]

torch.Size([2, 513, 839])
tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 1.0000e-10, 1.0000e-10,
        1.0000e-10], grad_fn=<AsStridedBackward0>)


100%|██████████| 100/100 [05:59<00:00,  3.59s/it]


In [33]:
PATH = "./modelsave.pt"
torch.save(model.state_dict(), "./modelsave.pt")

## Test model

In [34]:
PATH = "./modelsave.pt"
model = MaskNet()
model.load_state_dict(torch.load(PATH))
model.eval()

MaskNet(
  (lstm): LSTM(2, 8, num_layers=2, bidirectional=True)
  (fc): Linear(in_features=16, out_features=1, bias=True)
  (sigmoid): Sigmoid()
  (lstm2): LSTM(2, 8, num_layers=2, bidirectional=True)
  (fc2): Linear(in_features=16, out_features=1, bias=True)
  (sigmoid2): Sigmoid()
)

In [36]:
j = 120
#pred_null = model(stft((torch.cat((trainX[j][0].unsqueeze(1),trainX[j][1].unsqueeze(1)),1)).reshape(2,-1)).type(torch.complex64))

In [39]:
def save_sample(i):
    pred_null = model(stft((torch.cat((trainX[i][0].unsqueeze(1),trainX[i][1].unsqueeze(1)),1)).reshape(2,-1)).type(torch.float))
    torchaudio.save("sample_model_output.wav",pred_null.reshape(1,-1),sample_rate)
    torchaudio.save("sample_reference.wav", trainY[i].unsqueeze(1).reshape(1,-1),sample_rate)
    torchaudio.save("sample_input.wav", trainX[i][0].unsqueeze(1).reshape(1,-1),sample_rate)

In [40]:
save_sample(50)

tensor([1.0000e-10, 1.0000e-10, 1.0000e-10,  ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00], grad_fn=<AsStridedBackward0>)


## Librispeech Dataset + Noise

In [2]:
import os
import torchaudio
import random
import torch

N_PATH = "/Users/danilfedorovsky/Documents/10 Collection/00 Studium/00 Letztes Semester/Masterarbeit/Data/noise/free-sound/"
S_PATH = "/Users/danilfedorovsky/Documents/10 Collection/00 Studium/00 Letztes Semester/Masterarbeit/Data/LibriSpeech/dev-clean/"
def load_noise(N_PATH=N_PATH):
    noise = []
    for file in  os.listdir(N_PATH):
        if file[-4:] == ".wav":
            sound, _ = torchaudio.load(N_PATH+file)
            noise.append(sound)
    return noise


def load_speech(S_PATH=S_PATH):
    speech = []
    for folder in  os.listdir(S_PATH):
        if os.path.isdir(S_PATH+folder):
            for subfolder in os.listdir(S_PATH+folder):
                if os.path.isdir(S_PATH+folder+"/"+subfolder):
                    for file in os.listdir(S_PATH+folder+"/"+subfolder):
                        if file[-5:] == ".flac":
                            sound, _ = torchaudio.load(S_PATH+folder+"/"+subfolder+"/"+file)
                            speech.append(sound)
    return speech

/Users/danilfedorovsky/miniforge3/envs/pytorch/lib/python3.9/site-packages/torchaudio/_internal/module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")


In [3]:
speech = load_speech()
noise = load_noise()
print(len(speech))
print(len(noise))

2703
843


In [4]:
def add_noise_to_speech(speech, noise):
    X = []
    for sample in speech:
        len_noise = 0
        len_speech = 1
        sample_noise = torch.Tensor([])
        while len_noise<len_speech:
            sample_noise = random.choice(noise)
            len_speech = sample.shape[1]
            len_noise = sample_noise.shape[1]
        sample_noise = torch.narrow(sample_noise,1,0,len_speech)
        x = torch.add(sample,sample_noise*0.2)
        X.append(x)
    return X

In [5]:
X = add_noise_to_speech(speech,noise)
Y = speech

## Training on LibreSpeech

In [6]:
from torch.nn import Module, LeakyReLU, MaxPool1d, Conv2d, Linear, Softmax, BatchNorm1d, CrossEntropyLoss, BCELoss, Sigmoid, Tanh, LSTM, MSELoss
from torch import flatten
from torch.optim import Adam, RMSprop, SGD
import time
import torch
from pytorch_model_summary import summary
from tqdm import tqdm
import torchaudio

In [7]:
HIDDEN_SIZE=64
INIT_LR = 0.01
BATCH_SIZE = 1#64
SAMPLE_RATE = 16000
EPOCHS = 1
INPUT_CHANNEL = 1
REFERENCE_CHANNEL = 0

N_FFT = 1024
N_HOP = 256
stft = torchaudio.transforms.Spectrogram(
    n_fft=N_FFT,
    hop_length=N_HOP,
    power=None,
)
istft = torchaudio.transforms.InverseSpectrogram(n_fft=N_FFT, hop_length=N_HOP)
global i
i = 0

def prep_x(trainX,i):
        return stft((torch.cat((trainX[i][0].unsqueeze(1),trainX[i][1].unsqueeze(1)),1)).reshape(2,-1)).type(torch.complex64)

In [8]:
# # MASK NET

class MaskNet(Module):
    def __init__(self,noise=False):
        super(MaskNet, self).__init__()
        # First subnet for speech prediction
        self.type(torch.cfloat)
        self.noise = noise
        self.lstm = LSTM(input_size=INPUT_CHANNEL, hidden_size=HIDDEN_SIZE, num_layers=2, bidirectional=True)
        self.fc = Linear(in_features=HIDDEN_SIZE*2 ,out_features=1)
        self.sigmoid = Sigmoid()
        # Second subnet for noise prediction
        self.noise2 = noise
        self.lstm2 = LSTM(input_size=INPUT_CHANNEL, hidden_size=HIDDEN_SIZE, num_layers=2, bidirectional=True)
        self.fc2 = Linear(in_features=HIDDEN_SIZE*2 ,out_features=1)
        self.sigmoid2 = Sigmoid()

    def forward(self,x):
        # Speech prediction
        y = x.reshape(513,-1,INPUT_CHANNEL)#(513,251,INPUT_CHANNEL)
        y, (h_n, c_n) = self.lstm(y)
        y = self.fc(y).type(torch.double)
        speech_pred = self.sigmoid(y)
        speech_pred = speech_pred.reshape(513,-1).type(torch.cfloat)
        #print("speech_pred.shape",speech_pred.shape)

        # Noise prediction
        z = x.reshape(513,-1,INPUT_CHANNEL)
        z, (h_n, c_n) = self.lstm2(z)
        z = self.fc2(z).type(torch.double)
        noise_pred = self.sigmoid2(z)
        noise_pred = noise_pred.reshape(513,-1).type(torch.cfloat)

        psd_transform = torchaudio.transforms.PSD()
        psd_speech = psd_transform(x, speech_pred)
        psd_noise = psd_transform(x, noise_pred)
        mvdr_transform = torchaudio.transforms.SoudenMVDR()
        x = x.type(torch.cfloat)
        stft_souden = mvdr_transform(x, psd_speech, psd_noise, reference_channel=REFERENCE_CHANNEL)
        #print("stft_souden",stft_souden.shape)
        waveform_souden = istft(stft_souden, length=len(X[i][0]))#X[i].shape[-1])
        waveform_souden[waveform_souden != waveform_souden] = 1.0000e-10 
        return waveform_souden.reshape(-1)

print(summary(MaskNet(),torch.zeros((INPUT_CHANNEL, 513, 251))))


/Users/danilfedorovsky/miniforge3/envs/pytorch/lib/python3.9/site-packages/torchaudio/functional/functional.py:190: UserWarning: The length of signal is shorter than the length parameter. Result is being padded with zeros in the tail. Please check your center and hop_length settings. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/SpectralOps.cpp:1111.)
  waveform = torch.istft(


---------------------------------------------------------------------------------------------------
      Layer (type)                                    Output Shape         Param #     Tr. Param #
            LSTM-1     [513, 251, 128], [4, 251, 64], [4, 251, 64]         133,632         133,632
          Linear-2                                   [513, 251, 1]             129             129
         Sigmoid-3                                   [513, 251, 1]               0               0
            LSTM-4     [513, 251, 128], [4, 251, 64], [4, 251, 64]         133,632         133,632
          Linear-5                                   [513, 251, 1]             129             129
         Sigmoid-6                                   [513, 251, 1]               0               0
Total params: 267,522
Trainable params: 267,522
Non-trainable params: 0
---------------------------------------------------------------------------------------------------


In [9]:

#device =  torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

model = MaskNet()#.to(device)
model.type(torch.complex64)

opt = SGD(model.parameters(),lr=INIT_LR)#RMSprop(model.parameters(), lr=INIT_LR)#Adam(model.parameters(), lr=INIT_LR)

lossMSE = MSELoss()

H = {
    "train_loss":[],
    "train_acc":[],
    "val_loss":[],
    "val_acc":[]
}

print("[INFO] training the network...")
#startTime = time.time()

for epoch in range(0, EPOCHS):
    print("Epoch:",epoch,"/1")
    # Train Mode
    model.train()
    
    # Initialize
    totalTrainLoss = 0
    totalValLoss = 0
    trainCorrect = 0
    valCorrect = 0

    trainX = X
    trainY = Y

    global i
    for i in tqdm(range(0,50)):#len(trainX))):
        (x, y) = (stft(trainX[i]),trainY[i].reshape(-1))#(trainX[i],trainY[i])
        #(x, y) = (x.to(device), y.to(device))
        # perform a forward pass and calculate the training loss
        #print(next(model.parameters()).is_cuda)
        pred = model(x)
        print(pred)
        loss = lossMSE(pred, y)

        #print("Loss:",loss)
        # zero out the gradients, perform the backpropagation step,
        # and update the weights
        opt.zero_grad()
        loss.backward()
        opt.step()
        # add the loss to the total training loss so far and
        # calculate the number of correct predictions
        totalTrainLoss += loss
        # trainCorrect += (pred.argmax(1) == y).type(
        #     torch.float).sum().item()

[INFO] training the network...
Epoch: 0 /1


  0%|          | 0/50 [00:00<?, ?it/s]/var/folders/wr/spkz8f691xl_gwp76c19_yv40000gn/T/ipykernel_75399/418719489.py:22: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/Copy.cpp:250.)
  y = self.fc(y).type(torch.double)


tensor([ 3.4561e-12, -9.0862e-13, -5.5049e-13,  ..., -5.5481e-03,
        -4.7363e-03, -4.1809e-03], grad_fn=<ReshapeAliasBackward0>)


  2%|▏         | 1/50 [00:42<34:54, 42.75s/it]

tensor([-0.0074, -0.0123, -0.0107,  ...,  0.0252,  0.0083, -0.0196],
       grad_fn=<ReshapeAliasBackward0>)


  4%|▍         | 2/50 [00:52<18:48, 23.50s/it]

tensor([ 3.6621e-05,  3.6621e-05,  6.1035e-06,  ..., -5.0964e-03,
        -5.6458e-03, -6.2012e-03], grad_fn=<ReshapeAliasBackward0>)


  6%|▌         | 3/50 [04:30<1:27:54, 112.23s/it]

tensor([-3.0518e-05,  2.5403e-12,  3.0518e-05,  ...,  1.8127e-03,
        -2.3743e-03,  7.7637e-03], grad_fn=<ReshapeAliasBackward0>)


  8%|▊         | 4/50 [05:27<1:09:12, 90.28s/it] 

tensor([-0.0002, -0.0002, -0.0002,  ..., -0.0020, -0.0222, -0.0263],
       grad_fn=<ReshapeAliasBackward0>)


 10%|█         | 5/50 [05:44<48:00, 64.01s/it]  

tensor([-6.1035e-05, -5.4932e-05,  6.1035e-06,  ...,  3.0518e-05,
         3.0518e-05,  3.0518e-05], grad_fn=<ReshapeAliasBackward0>)


 12%|█▏        | 6/50 [17:51<3:32:14, 289.41s/it]

tensor([ 3.7253e-10, -7.4551e-10,  2.4415e-05,  ..., -1.0187e-02,
        -1.1957e-02, -1.1957e-02], grad_fn=<ReshapeAliasBackward0>)


 14%|█▍        | 7/50 [18:09<2:23:53, 200.77s/it]

tensor([ 0.0003,  0.0002,  0.0002,  ..., -0.0248, -0.0152, -0.0006],
       grad_fn=<ReshapeAliasBackward0>)


 16%|█▌        | 8/50 [21:22<2:18:40, 198.12s/it]

tensor([-0.0124, -0.0321, -0.0391,  ..., -0.0375, -0.0361, -0.0366],
       grad_fn=<ReshapeAliasBackward0>)


 18%|█▊        | 9/50 [21:40<1:36:57, 141.89s/it]

tensor([ 3.6621e-05, -1.1597e-04, -1.7090e-04,  ..., -8.6304e-03,
        -1.0510e-02,  3.2593e-03], grad_fn=<ReshapeAliasBackward0>)


 20%|██        | 10/50 [22:49<1:19:31, 119.29s/it]

tensor([-0.0101, -0.0015,  0.0194,  ...,  0.0024,  0.0009,  0.0034],
       grad_fn=<ReshapeAliasBackward0>)


 22%|██▏       | 11/50 [24:29<1:13:39, 113.33s/it]

tensor([ 6.1035e-05, -6.2047e-12,  3.0518e-05,  ..., -2.8076e-04,
        -2.8687e-04, -2.5024e-04], grad_fn=<ReshapeAliasBackward0>)


 24%|██▍       | 12/50 [24:51<54:17, 85.73s/it]   

tensor([ 1.6711e-02,  2.6715e-02,  2.1716e-02,  ...,  2.4419e-05,
        -8.4595e-03, -1.1261e-02], grad_fn=<ReshapeAliasBackward0>)


 26%|██▌       | 13/50 [25:04<39:13, 63.62s/it]

tensor([-0.0014, -0.0029, -0.0026,  ...,  0.0011,  0.0008,  0.0008],
       grad_fn=<ReshapeAliasBackward0>)


 28%|██▊       | 14/50 [26:35<43:08, 71.91s/it]

tensor([ 6.1035e-06,  6.1035e-06,  6.1035e-06,  ..., -2.9663e-03,
        -4.8584e-03, -6.2683e-03], grad_fn=<ReshapeAliasBackward0>)


 30%|███       | 15/50 [31:39<1:22:43, 141.81s/it]

tensor([ 4.2725e-05,  4.8828e-05,  6.7139e-05,  ..., -2.1362e-04,
        -8.4228e-04, -6.8359e-04], grad_fn=<ReshapeAliasBackward0>)


 32%|███▏      | 16/50 [32:35<1:05:44, 116.01s/it]

tensor([-3.4790e-04, -8.0566e-04,  3.6621e-05,  ..., -1.1353e-03,
        -3.0701e-03, -2.4292e-03], grad_fn=<ReshapeAliasBackward0>)


 34%|███▍      | 17/50 [33:14<51:04, 92.85s/it]   

tensor([-0.0011, -0.0011, -0.0011,  ..., -0.0017, -0.0017,  0.0006],
       grad_fn=<ReshapeAliasBackward0>)


 36%|███▌      | 18/50 [34:12<43:54, 82.31s/it]

tensor([-2.8076e-04, -2.8687e-04, -2.7466e-04,  ..., -7.9346e-05,
        -6.1035e-05,  4.8828e-05], grad_fn=<ReshapeAliasBackward0>)


 38%|███▊      | 19/50 [35:31<42:00, 81.31s/it]

tensor([-0.0021, -0.0035, -0.0024,  ...,  0.0614,  0.0608,  0.0584],
       grad_fn=<ReshapeAliasBackward0>)


 40%|████      | 20/50 [36:01<33:03, 66.12s/it]

tensor([ 4.1837e-12,  3.6621e-05, -3.0518e-05,  ..., -7.3242e-05,
        -2.4414e-05,  4.2725e-05], grad_fn=<ReshapeAliasBackward0>)


 42%|████▏     | 21/50 [37:12<32:34, 67.38s/it]

tensor([6.1035e-05, 5.4932e-05, 3.0518e-05,  ..., 2.9907e-03, 2.9602e-03,
        3.0457e-03], grad_fn=<ReshapeAliasBackward0>)


 44%|████▍     | 22/50 [38:23<32:01, 68.64s/it]

tensor([-1.7700e-04, -9.1553e-05, -3.0518e-05,  ...,  9.6436e-03,
        -7.0190e-04,  1.6968e-03], grad_fn=<ReshapeAliasBackward0>)


 46%|████▌     | 23/50 [39:49<33:14, 73.87s/it]

tensor([-3.0518e-05,  6.1035e-06,  3.0518e-05,  ...,  2.0471e-02,
         1.7725e-02,  1.6638e-02], grad_fn=<ReshapeAliasBackward0>)


 48%|████▊     | 24/50 [41:04<32:06, 74.09s/it]

tensor([0.0014, 0.0014, 0.0012,  ..., 0.0040, 0.0218, 0.0198],
       grad_fn=<ReshapeAliasBackward0>)


 50%|█████     | 25/50 [41:53<27:47, 66.71s/it]

tensor([0.0030, 0.0020, 0.0022,  ..., 0.0694, 0.0674, 0.0652],
       grad_fn=<ReshapeAliasBackward0>)


 52%|█████▏    | 26/50 [43:22<29:20, 73.34s/it]

tensor([0.0033, 0.0031, 0.0027,  ..., 0.0124, 0.0208, 0.0293],
       grad_fn=<ReshapeAliasBackward0>)


 54%|█████▍    | 27/50 [44:41<28:41, 74.84s/it]

tensor([ 0.0043, -0.0041, -0.0089,  ..., -0.0305, -0.0293, -0.0008],
       grad_fn=<ReshapeAliasBackward0>)


 56%|█████▌    | 28/50 [44:48<20:03, 54.70s/it]

tensor([-0.0253, -0.0634, -0.0421,  ...,  0.0544,  0.0731,  0.0214],
       grad_fn=<ReshapeAliasBackward0>)


 58%|█████▊    | 29/50 [45:43<19:08, 54.69s/it]

tensor([ 5.0659e-04, -3.0518e-05, -7.9346e-05,  ...,  2.1320e-02,
         2.0715e-02,  2.7118e-02], grad_fn=<ReshapeAliasBackward0>)


 60%|██████    | 30/50 [48:05<26:59, 80.96s/it]

tensor([-0.0014, -0.0032, -0.0015,  ..., -0.0040, -0.0044, -0.0065],
       grad_fn=<ReshapeAliasBackward0>)


 62%|██████▏   | 31/50 [49:06<23:43, 74.93s/it]

tensor([-0.0020, -0.0019, -0.0014,  ..., -0.0054,  0.0143,  0.0127],
       grad_fn=<ReshapeAliasBackward0>)


 64%|██████▍   | 32/50 [49:38<18:34, 61.90s/it]

tensor([-0.0009, -0.0029, -0.0028,  ..., -0.0250,  0.0076, -0.0087],
       grad_fn=<ReshapeAliasBackward0>)


 66%|██████▌   | 33/50 [51:13<20:23, 71.96s/it]

tensor([-0.0007, -0.0008, -0.0016,  ..., -0.0130, -0.0134, -0.0133],
       grad_fn=<ReshapeAliasBackward0>)


 68%|██████▊   | 34/50 [52:38<20:16, 76.01s/it]

tensor([0.0037, 0.0038, 0.0039,  ..., 0.0021, 0.0024, 0.0029],
       grad_fn=<ReshapeAliasBackward0>)


 70%|███████   | 35/50 [53:38<17:48, 71.21s/it]

tensor([-0.0039, -0.0042, -0.0039,  ..., -0.0038, -0.0039, -0.0039],
       grad_fn=<ReshapeAliasBackward0>)


 72%|███████▏  | 36/50 [54:02<13:16, 56.89s/it]

tensor([-0.0019, -0.0020, -0.0023,  ..., -0.0002, -0.0003, -0.0004],
       grad_fn=<ReshapeAliasBackward0>)


 74%|███████▍  | 37/50 [54:12<09:15, 42.72s/it]

tensor([ 0.0017,  0.0014,  0.0014,  ..., -0.0019, -0.0019, -0.0020],
       grad_fn=<ReshapeAliasBackward0>)


 76%|███████▌  | 38/50 [54:25<06:45, 33.78s/it]

tensor([ 0.0099,  0.0065,  0.0066,  ..., -0.0026, -0.0106, -0.0018],
       grad_fn=<ReshapeAliasBackward0>)


 78%|███████▊  | 39/50 [57:56<15:59, 87.20s/it]

tensor([-0.0007, -0.0039, -0.0040,  ..., -0.0016, -0.0036, -0.0036],
       grad_fn=<ReshapeAliasBackward0>)


 80%|████████  | 40/50 [59:36<15:08, 90.86s/it]

tensor([-0.0002, -0.0009, -0.0003,  ...,  0.0288,  0.0322,  0.0342],
       grad_fn=<ReshapeAliasBackward0>)


 82%|████████▏ | 41/50 [1:00:31<12:01, 80.14s/it]

tensor([ 0.0058,  0.0072,  0.0060,  ..., -0.0212, -0.0222, -0.0191],
       grad_fn=<ReshapeAliasBackward0>)


 84%|████████▍ | 42/50 [1:01:39<10:12, 76.56s/it]

tensor([ 0.0081,  0.0174,  0.0173,  ..., -0.0109, -0.0119, -0.0127],
       grad_fn=<ReshapeAliasBackward0>)


 86%|████████▌ | 43/50 [1:03:05<09:14, 79.22s/it]

tensor([ 0.0062,  0.0063,  0.0039,  ..., -0.0005,  0.0072,  0.0136],
       grad_fn=<ReshapeAliasBackward0>)


 88%|████████▊ | 44/50 [1:04:03<07:18, 73.12s/it]

tensor([-0.0024, -0.0021, -0.0018,  ..., -0.0031, -0.0029, -0.0026],
       grad_fn=<ReshapeAliasBackward0>)


 90%|█████████ | 45/50 [1:04:15<04:33, 54.63s/it]

tensor([-0.0021, -0.0020, -0.0018,  ...,  0.0024,  0.0019,  0.0026],
       grad_fn=<ReshapeAliasBackward0>)


 92%|█████████▏| 46/50 [1:06:59<05:49, 87.38s/it]

tensor([0.0025, 0.0016, 0.0019,  ..., 0.0139, 0.0134, 0.0201],
       grad_fn=<ReshapeAliasBackward0>)


 94%|█████████▍| 47/50 [1:08:02<04:00, 80.00s/it]

tensor([ 0.0001,  0.0006,  0.0002,  ..., -0.0471,  0.0032,  0.0282],
       grad_fn=<ReshapeAliasBackward0>)


 96%|█████████▌| 48/50 [1:09:02<02:28, 74.26s/it]

tensor([-0.0005, -0.0003, -0.0003,  ..., -0.0006, -0.0008, -0.0007],
       grad_fn=<ReshapeAliasBackward0>)


 98%|█████████▊| 49/50 [1:14:22<02:28, 148.02s/it]

tensor([-0.0015, -0.0016, -0.0017,  ..., -0.0002, -0.0005, -0.0009],
       grad_fn=<ReshapeAliasBackward0>)


100%|██████████| 50/50 [1:14:58<00:00, 89.96s/it] 


In [10]:
PATH = "./modelsaveLib.pt"
torch.save(model.state_dict(), PATH)

In [38]:
def save_sample(i,sample_rate=16000):
    pred_null = model(stft(trainX[i]))
    torchaudio.save("sample_model_output.wav",pred_null.reshape(1,-1),sample_rate)
    torchaudio.save("sample_reference.wav", trainY[i].reshape(1,-1),sample_rate)
    torchaudio.save("sample_input.wav", trainX[i].reshape(1,-1),sample_rate)

In [39]:
save_sample(10)